### ISSUE TITLE
yo ionic gives Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Jerome2606** [diegonetto/generator-ionic#138]
Hi,

I'm behind a proxy and when I execute yo ionic, it gives me error:

```
C:\Users\jela\Documents\Project\AppMobile\ionic-demo>ionic -v
1.2.13

C:\Users\jela\Documents\Project\AppMobile\ionic-demo>yo ionic
    _             _
   (_)           (_)
    _  ___  _ __  _  ___
   | |/ _ \| '_ \| |/ __|
   | | (_) | | | | | (__
   |_|\___/|_| |_|_|\___|

[?] Would you like to use Sass with Compass (requires Ruby)? Yes
Created a new Cordova project with name "IonicDemo" and id "com.example.IonicDem
o"
[?] Which Cordova plugins would you like to include?
[?] Which starter template [T] or example app [A] would you like to use? (Use ar
[?] Which starter template [T] or example app [A] would you like to use? [T] Bla
nk

Install plugins registered at plugins.cordova.io: grunt plugin:add:org.apache.co
rdova.globalization
Or install plugins direct from source: grunt plugin:add:https://github.com/apach
e/cordova-plugin-console.git

Installing starter template. Please wait

     info ... Fetching http://github.com/diegonetto/ionic-starter-blank/archive/
master.tar.gz ...
     info This might take a few moments

Error: connect ETIMEDOUT
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

If I test the command **ionic start demo123**, everything works fine.
- I configure proxy on git, cordova.
- I delete the node_module/cordova from generator_ionic, like that it's used the last version.
- I use this hack to make ionic start works: [http://www.jasonwatmore.com/post/2014/04/02/Ionic-Framework-Getting-ionic-start-appName-Working-Behind-a-Proxy.aspx](http://www.jasonwatmore.com/post/2014/04/02/Ionic-Framework-Getting-ionic-start-appName-Working-Behind-a-Proxy.aspx)

Any ideas?

**Comment by berlanga2008** [comment]
use this
`>set PROXY=http://your-proxy.com:8080`
