### ISSUE TITLE
grunt platform:add:"browser" stops due to "icons_and_splashscreens.js" hook

### ISSUE THREAD

**Issue by Alir3z4** [diegonetto/generator-ionic#198]
I'v tried to add "browser platform" for `cordova`, with both cordova cli and grunt task and it ended up with:
```
>> path.js:439
>>       throw new TypeError('Arguments to path.resolve must be strings');
```
error and couldn't make it work,

Here's the full traceback.
```
[alireza@arch tiwun_mobile]$ cordova platform list
Installed platforms: android 4.0.0
Available platforms: amazon-fireos, blackberry10, browser, firefoxos, ubuntu
[alireza@arch tiwun_mobile]$ grunt  platform:add:"browser"
Running "platform:add:browser" (platform) task
Running command: /home/alireza/dev/pycharm/tiwun/tiwun_mobile/hooks/before_platform_add/init_directories.js /home/alireza/dev/pycharm/tiwun/tiwun_mobile

Creating browser project...

Creating Browser project

Project Path platforms/browser

Package Name com.tiwun.mobile

Project Name Tiwun

Running command: /home/alireza/dev/pycharm/tiwun/tiwun_mobile/hooks/after_prepare/icons_and_splashscreens.js /home/alireza/dev/pycharm/tiwun/tiwun_mobile

>> path.js:439
>>       throw new TypeError('Arguments to path.resolve must be strings');
>>             ^
>> TypeError: Arguments to path.resolve must be strings
>>     at Object.posix.resolve (path.js:439:13)
>>     at /home/alireza/dev/pycharm/tiwun/tiwun_mobile/hooks/after_prepare/icons_and_splashscreens.js:54:19
>>     at arrayEach (/home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/lodash/index.js:1289:13)
>>     at Function.forEach (/home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/lodash/index.js:5710:11)
>>     at Object.<anonymous> (/home/alireza/dev/pycharm/tiwun/tiwun_mobile/hooks/after_prepare/icons_and_splashscreens.js:53:3)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)
>>     at Function.Module.runMain (module.js:501:10)
>> Error: Hook failed with error code 1: /home/alireza/dev/pycharm/tiwun/tiwun_mobile/hooks/after_prepare/icons_and_splashscreens.js
>>     at /home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:194:23
>>     at _rejected (/home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/cordova/node_modules/q/q.js:797:24)
>>     at /home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/cordova/node_modules/q/q.js:823:30
>>     at Promise.when (/home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/cordova/node_modules/q/q.js:1035:31)
>>     at Promise.promise.promiseDispatch (/home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/cordova/node_modules/q/q.js:741:41)
>>     at /home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/cordova/node_modules/q/q.js:557:44
>>     at flush (/home/alireza/dev/pycharm/tiwun/tiwun_mobile/node_modules/cordova/node_modules/q/q.js:108:17)
>>     at process._tickCallback (node.js:355:11)
Warning: Task "platform:add:browser" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-05-10 04:37:05 UTC)
platform:add:browser  2.7s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 100%
Total 2.7s

[alireza@arch tiwun_mobile]$ 

```

**Comment by Alir3z4** [comment]
Okay, I get this fixed and running and could easily run `grunt build` and have each platform package after applying #199.

**Comment by Alir3z4** [comment]
This is also happens for adding `windows` platform as well. I just dummy fix this by adding `windows` to `hooks/after_prepare/update_platform_config.js` conf keys. I'm not sure what is the real workaround with this.
