### ISSUE TITLE
Invalid Data error using Update Platform Config hook

### ISSUE THREAD

**Issue by felquis** [diegonetto/generator-ionic#253]
I found this [hook here](https://gist.github.com/mlynch/284699d676fe9ed0abfa#gistcomment-1577202) and I installed `/hooks/after_prepare/update_platform_config.js`

I'm making fixes related to iOS9 App Transport Security, more info [here](http://blog.ionic.io/preparing-for-ios-9/) and at [amazon here](http://mobile.awsblog.com/post/Tx2QM69ZE6BGTYX/Preparing-Your-Apps-for-iOS-9)

```xml
<platform name="ios">
  <config-file platform="ios" target="*-Info.plist" parent="CFBundleURLTypes">
      <key>NSAppTransportSecurity</key>
      <dict>
        <key>NSExceptionDomains</key>
        <dict>
          <key>amazonaws.com</key>
          <dict>
            <key>NSThirdPartyExceptionMinimumTLSVersion</key>
            <string>TLSv1.0</string>
            <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
            <false/>
            <key>NSIncludesSubdomains</key>
            <true/>
          </dict>
          <key>amazonaws.com.cn</key>
          <dict>
            <key>NSThirdPartyExceptionMinimumTLSVersion</key>
            <string>TLSv1.0</string>
            <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
            <false/>
            <key>NSIncludesSubdomains</key>
            <true/>
          </dict>
        </dict>
      </dict>
  </config-file>
</platform>
```

But, I'm getting this error:

![image](https://cloud.githubusercontent.com/assets/736728/10404521/9d8f074a-6ea9-11e5-9c63-4ac41d8518a1.png)

Does anyone know what I'm doing wrong?

**Comment by felquis** [comment]
So, the problem is that the hook only support Android and iOS and I'm also using browser platform.

Also, I figured out that we do not need to read the files into `./platforms` to know what is the platforms used.

Just do:
```js
// Main
(function () {

    if (rootdir) {
        // go through each of the platform directories that have been prepared
        var platforms = process.env.CORDOVA_PLATFORMS.split(',');
```

More infos in the section Non-JavaScript [here](https://cordova.apache.org/docs/en/edge/guide/appdev/hooks/index.html)

if I run
```sh
cordova prepare
```

`process.env.CORDOVA_PLATFORMS` will be all the platforms used delimited with comma , example android,ios,browser

if I run

```sh
cordova prepare ios
```

`process.env.CORDOVA_PLATFORMS` will be just `ios`

and running

```sh
cordova prepare android ios
```

`process.env.CORDOVA_PLATFORMS` will be `android,ios`

As it only works for Android and iOS, I ignored all the other platforms.

Final
```js
// Main
(function () {
    var supportedPlatforms = ['android', 'ios'];
    if (rootdir) {
        // go through each platform that have been prepared
        var platforms = process.env.CORDOVA_PLATFORMS.split(',');

        platforms = _.filter(platforms, function (platform) {
          return supportedPlatforms.indexOf(platform) !== -1;
        });

        _.each(platforms, function (platform) {
            try {
                platform = platform.trim().toLowerCase();
                platformConfig.updatePlatformConfig(platform);
            } catch (e) {
                process.stdout.write(e);
            }
        });
    }
}());
```

Looks like it was already fixed in a pull request #228 #199 so I'm wont send pull request to fix it, I'll keep this issue open since any of these pull requests were merged.

**Comment by azachar** [comment]
Hi there, I am having a similar issue 

```
    throw new TypeError('invalid data');
    ^

TypeError: invalid data
    at Socket.write (net.js:617:11)
    at .../hooks/after_prepare/update_platform_config.js:373:24
```

Could you please advice what to do?

This is my config.xml

```
  <platform name="android">
        <preference name="android-minSdkVersion" value="22" />
        <preference name="android-targetSdkVersion" value="22" />
        <config-file target="AndroidManifest.xml" parent="/manifest">
          <uses-sdk android:minSdkVersion="22" android:targetSdkVersion="23" />
          <uses-permission android:name="android.permission.RECORD_AUDIO" />
          <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
          <uses-permission android:name="android.permission.CAMERA" />
          <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
        </config-file>
    </platform>
```

Thanks a lot!
