### ISSUE TITLE
Yo ionic throws error

### ISSUE THREAD

**Issue by shubhamkes** [diegonetto/generator-ionic#274]
Hi,
everything is going perfectly except yo ionic command.

On running this command, am getting error.

Stack trace
info trying registry request attempt 3 at 4:09:50 PM
http GET http://registry.cordova.io/org.apache.cordova.device

{till above line, execution goes very well and after this line i get following error}

/usr/local/lib/node_modules/generator-ionic/node_modules/q/q.js:126
                    throw e;
                    ^

Error: connect ETIMEDOUT 50.17.177.14:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1061:14)

**Comment by ghost** [comment]
I have the same issue too when executing `yo ionic myApp`:

ionic/node_modules/q/q.js:126
                    throw e;
                    ^

Error: connect ETIMEDOUT 50.17.177.14:80
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
